<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CVPC8E9" failures="1" tests="1" name="Default test(failed)" time="65.304" errors="0" timestamp="2024-07-13T19:13:33 BST">
  <testcase classname="com.inetbanking.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="46.665">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.inetbanking.testCases.TC_AddCustomerTest_003.addNewCustomer(TC_AddCustomerTest_003.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- addNewCustomer -->
</testsuite> <!-- Default test(failed) -->
